### ISSUE TITLE
Visual Block Mode Selection Lost When Moving Upwards (v2.0 regression)

### ISSUE THREAD

**Issue by kstevens715** [max397574/better-escape.nvim#102]
I'm encountering an issue with `better-escape.nvim` after updating to version 2.0. In visual block mode, when I move down to select a block and then move back up, the current visual selection is lost, forcing me to start over. This issue does not occur with version 1.0, where block selection works as expected.

**Steps to Reproduce:**

1. Enter visual block mode (Ctrl+v).
2. Move the cursor down to expand the block selection.
3. Attempt to move the cursor back up.

**Expected Behavior:** The block selection should remain intact when moving back up, as it does in version 1.0.

**Actual Behavior:** The block selection is lost when moving up, requiring re-selection.

**Environment:**
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

Let me know if any further details are needed.

Thank you for your work on this plugin!

**Comment by max397574** [comment]
just disable the visual mode mappings

**Comment by buesing** [comment]
I also have this problem. Shouldn't this be disabled by default?
