### ISSUE TITLE
`j` Key Unusable in Snippets' Select Mode

### ISSUE THREAD

**Issue by domi413** [max397574/better-escape.nvim#103]
Hello, I am experiencing an issue when using snippets. When a snippet is used, I enter into the select mode to choose a placeholder. The problem now is, that I cannot use the `j` key to go into Insert mode. Instead, I'm stuck in the select-mode.

### Current Configuration:
Here's my setup for `better-escape.nvim`:
```lua
return {
	"max397574/better-escape.nvim",
	event = "InsertEnter",
	config = function()
		require("better_escape").setup({
			mappings = {
				t = { j = { false } }, -- lazygit navigation fix
				v = { j = { k = false } }, -- visual select fix
			},
		})
	end,
}
```

Thank you for looking into this issue!

**Comment by max397574** [comment]
just disable the mapping for selection mode
```
s = {
    j = { k = false },
},
```
