### ISSUE TITLE
README should quickly answer "what does this solve"

### ISSUE THREAD

**Issue by dbalatero** [max397574/better-escape.nvim#12]
Hi! As quick feedback, the README for this repo makes me want to close Chrome because it's not _immediately_ obvious what this plugin does.

You might want to take [another read](https://github.com/max397574/better-escape.nvim), but pretend you've never heard of the plugin before.

The repository you link out to (https://github.com/jdhao/better-escape.vim) has a better introduction:

> A lot of people have been mapping jk or kj or kk to ESC in order to escape insert mode quickly. However, when we press the first key in these mappings, Vim/Nvim will wait for timeoutlen milliseconds before writing this char to buffer. The apparent lag caused by this behaviour is annoying.

> Better-escape.vim is created to help Vim/Nvim users escape insert mode quickly using their customized key combinations, without experiencing the lag.

You should have something like that front and center on this project's README. If don't immediately understand a plugin's purpose when browsing the repo, I will often just close the tab and move on. Get people excited about it!

**Comment by max397574** [comment]
Added it to the readme.

**Comment by max397574** [comment]
This is just a picture
The gifs are below (demo)
This just shows the moment

**Comment by max397574** [comment]
ig I should add links
