### ISSUE TITLE
The plugin better-escape.vim should be given its credit.

### ISSUE THREAD

**Issue by jdhao** [max397574/better-escape.nvim#14]
I saw your plugin from reddit. I think the original idea is from my plugin [better-escape.vim](https://github.com/jdhao/better-escape.vim), which is implemented in vim script. I understand that a lot of people want to configure their neovim using purely lua, and I think it is a good idea to rewrite the original plugin in lua.  However, the original plugin should be given its due credit. I see that the reference of better-escape.vim is remove in [this commit](https://github.com/max397574/better-escape.nvim/commit/6cc654ed3632c0b4e783e1098bbc8f7d260729c6).

I am not sure why. Is it intentional or by accident?

**Comment by jdhao** [comment]
Until I saw the reddit post the author posted today, I am not even aware that such an alternative lua plugin exists...

**Comment by max397574** [comment]
by accident

**Comment by jdhao** [comment]
Thanks for adding back the reference.  I think this is a good plugin for pure-lua neovim users. I will add a link referencing to this plugin in my repo in case people need it.
