### ISSUE TITLE
Does not work with macros

### ISSUE THREAD

**Issue by bkesby** [max397574/better-escape.nvim#21]
Whenever entering a new macro that contains an exit with better escape keybinding, the macro does not register an escape but instead enters the keys as is. 

e.g. 
if mapping == 'jk'
and macro combination entered is `this is a test<jk>[o]this is on a newline`
where `[o]` is meant to be a normal mode operation
and `<jk>` is the exit mapping

expected:
`this is a test`
`this is on a newline`

result:
`this is a testjkothis is on a newline`

is this something wrong with my setup or just the nature of using this plugin for exiting insert mode?

**Comment by max397574** [comment]
This is the nature of using this plugin.
Sadly
There are also problems when repeating. I don't know exactly why this happens.
But at the moment there is no fix for this.
But I'll try to find one.

**Comment by bkesby** [comment]
Here goes attempting to generate the muscle memory to only use C-[ during macros lol.

Thanks anyway
