### ISSUE TITLE
Inserts char while typing

### ISSUE THREAD

**Issue by adrian5** [max397574/better-escape.nvim#22]
I stumbled upon this plugin and just gave it a try. I find the insertion of characters quite distracting, especially within longer lines.

Plugin:

![plugin-escape](https://user-images.githubusercontent.com/5426924/142872487-d1ededa8-eaf6-4d57-8c10-0c75d4eeb7fa.gif)

Native:

![native-escape](https://user-images.githubusercontent.com/5426924/142872500-e0b6c2d5-1e81-49e6-954a-86793f6d41f9.gif)

If this is intentional (unavoidable), then feel free to close this issue. Personally I find that more distracting than any strangeness around typing `jj` or `jk`, which so rarely happens.

**Comment by max397574** [comment]
it is intentional and unavoidable this is the whole point of the plugin
that the chars really get inserted and that it doesn't have delay when typing a word with j because of this

**Comment by adrian5** [comment]
Fair enough. Did you run into this need yourself? Typing in English and programming, I just never ran into the need of typing a literal `jj` or `jk`. `j` followed by other chars remains instant.

**Comment by max397574** [comment]
then just don't use this plugin
