### ISSUE TITLE
Escape Terminal Mode ?

### ISSUE THREAD

**Issue by rzksobhy78** [max397574/better-escape.nvim#23]
How can I use this plugin to escape terminal mode in terminal
I'm using this one
https://github.com/akinsho/toggleterm.nvim

**Comment by max397574** [comment]
you can't because this plugin uses CharInsertPre, which only works in buffers

**Comment by ColinKennedy** [comment]
Adding `InsertCharPre` in Terminal mode is planned work https://github.com/neovim/neovim/issues/5018. Once the issue is closed and complete could this issue be reopened?

**Comment by max397574** [comment]
yes
I'm also working on a rework of the thing locally
it maybe also be possible with the new version

**Comment by ilan-schemoul** [comment]
https://github.com/TheBlob42/houdini.nvim makes it possible in so many modes including terminal, cmd etc.

**Comment by max397574** [comment]
with the pr for the rewrite better-escape will also have support for most modes and also allow mapping anything and not just to esc
