### ISSUE TITLE
Error when typing `ini` since the last update

### ISSUE THREAD

**Issue by smjonas** [max397574/better-escape.nvim#28]
Hey, I just got this error after quickly typing `ini` in a buffer (I remapped ii to escape).
Previously, everything was working fine.
```
Error detected while processing InsertCharPre Autocommands for "*":
E5108: Error executing lua ...ck/packer/start/better-escape.nvim/lua/better_escape.lua:22: attempt to call field 'stop_timer' (a nil value)
stack traceback:
        ...ck/packer/start/better-escape.nvim/lua/better_escape.lua:22: in function 'start_timeout'
        ...ck/packer/start/better-escape.nvim/lua/better_escape.lua:104: in function 'check_charaters'
        [string ":lua"]:1: in main chunk
```

**Comment by max397574** [comment]
@smjonas should be fixed now can you confirm?

**Comment by smjonas** [comment]
Thanks, that error is now gone but I see another error now:
```
Error executing vim.schedule lua callback: vim.lua:413: handle 0x557acfaaf180 is already closing
stack traceback:
        [C]: in function 'close'
        vim.lua:413: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by max397574** [comment]
I'll check that out tomorrow

**Comment by max397574** [comment]
when exactly do you see that error?
what mappings do you have and what exactly do you type?

**Comment by smjonas** [comment]
I use `ino ii <Esc>\`^` and  `set timeoutlen = 250` (if that's relevant).

**Comment by max397574** [comment]
Hmmmm interesting I can't reproduce that. Even with a key mapping so they are typed like instantly.

**Comment by smjonas** [comment]
I can't reproduce it with a minimal config either, it seems to be related to an interaction with another plugin. If I find out eventually what plugin caused this, I will let you know!

**Comment by max397574** [comment]
ok thank you

**Comment by max397574** [comment]
could you send the output of `:imap` @smjonas ?

**Comment by smjonas** [comment]
Sure, `:imap ii` shows `` i ii * <Esc>`^ `` (I don't remember what the `` `^ `` was for, I got this from somewhere online).

**Comment by max397574** [comment]
why have you mapped it?
The whole point of better-escape.nvim is that you don't have to map it

**Comment by smjonas** [comment]
Oh that was the problem. It didn't say this anywhere in the readme, I just assumed it would modify my existing mappings in some way. Could you please add this info the readme or unmap the user mapping in the code? Thanks :)
