### ISSUE TITLE
Don't modify file if nothing changes

### ISSUE THREAD

**Issue by yngwi** [max397574/better-escape.nvim#31]
Do you see a way to avoid "modifying" a file if directly after entering insert mode, the insert mode is left again by using "jk"? Sometimes I enter insert mode but then after some thinking don't changing anything. This will still create an entry in the file undo tree which is unintuitive, I think. Of course, this is not a big issue but still. What do you think?

Thanks,
Daniel

**Comment by max397574** [comment]
already answered in https://github.com/max397574/better-escape.nvim/issues/5

**Comment by yngwi** [comment]
Oh sorry I didn't see this. Thank you.
