### ISSUE TITLE
Use the black hole register when deleting an empty line

### ISSUE THREAD

**Issue by VonHeikemen** [max397574/better-escape.nvim#32]
Please. 

So, deleting the whitespace of an empty line makes you "lose" the last yank. It would be better to use the "[black hole register](https://neovim.io/doc/user/change.html#quote_)" so the order of the normal registers stays the same.

https://github.com/max397574/better-escape.nvim/blob/2bee35e435310c7cc1333fff983268ae3f17b06f/lua/better_escape.lua#L69

Replacing `0D` with `0"_D` should do the trick.

**Comment by max397574** [comment]
okay I will push that in two minutes
