### ISSUE TITLE
Auto-completion popup window edge case

### ISSUE THREAD

**Issue by g6ai** [max397574/better-escape.nvim#34]
When I'm typing a word and there's popup window for auto-completion, 'jk' does not trigger escape; instead 'jk' itself is entered.

**Comment by g6ai** [comment]
I use coc.nvim for it

**Comment by max397574** [comment]
I have no clue what that could be since I use nvim-cmp and it works there

**Comment by g6ai** [comment]
Cool thanks

**Comment by xiyaowong** [comment]
because coc use <space><bs> to cancel completion, it has been fixed now

**Comment by g6ai** [comment]
@xiyaowong can confirm. Thank you very much!

**Comment by g6ai** [comment]
@xiyaowong This issue occurs again. Could you inform me of the exact CoC issue and I can follow it there?

**Comment by xiyaowong** [comment]
https://github.com/neoclide/coc.nvim/blob/210e2d0337b0bc55b468a78c0668029059582aa1/autoload/coc.vim#L133 @g6ai

**Comment by max397574** [comment]
is this still a problem @g6ai

**Comment by g6ai** [comment]
I tested it just now, it is solved. I think is used to be a problem on the CoC.nvim side, so yeah I should close it.
