### ISSUE TITLE
Is it possible to map different mappings with different keys?

### ISSUE THREAD

**Issue by milanglacier** [max397574/better-escape.nvim#37]
require("better_escape").setup {
    mapping = {"jk"}, -- a table with mappings to use
    timeout = vim.o.timeoutlen, -- the time in which the keys must be hit in ms. Use option timeoutlen by default
    clear_empty_lines = false, -- clear line after escaping if there is only whitespace
    keys = "<Esc>", -- keys used for escaping, if it is a function will use the result everytime
    -- example()
    -- keys = function()
    --   return vim.api.nvim_win_get_cursor(0)[2] > 1 and '<esc>l' or '<esc>'
    -- end,
}

This is my current config.
But I have mapped 'kj' to abort/close nvim-cmp's auto-complete popup menu, so I would be interested in having another mapping 
"kj" to support that functionality.

**Comment by max397574** [comment]
So you want to map kj to esc (with better-escape.nvim)?

**Comment by milanglacier** [comment]
> So you want to map kj to esc (with better-escape.nvim)?

I want to map jk to escape, and kj mapped to nvm.cmp.close()/nvim.cmp.abort()

**Comment by max397574** [comment]
so basically sou want two different `keys`

**Comment by xiyaowong** [comment]
It's easy but out of scope for this plugin.
