### ISSUE TITLE
Interference with completion plugin

### ISSUE THREAD

**Issue by Mr1cecream** [max397574/better-escape.nvim#40]
If a word/snippet being completed include one of the escape mappings, better-escape will fire off and cut off the completion.
This happened to me with cmp.nvim, but I assume other completion plugins function similarly and therefore will have the same issue.

I am not sure if this is fixable, but it is annoying for Colemak users such as myself who want to keep the popular 'jk' position as an escape binding, as those keys would be bound to 'ne' , which is a common key combination in words such as "new", "clone" and many more.

**Comment by max397574** [comment]
Since the completion engines insert the characters this plugin will always be triggered. There isn't anything that I'd know of to fix this issue. This is just how this plugin works.
