### ISSUE TITLE
General API for custom escapes

### ISSUE THREAD

**Issue by axieax** [max397574/better-escape.nvim#41]
Hi, I'm looking to use this plugin to make custom escapes. As an example, I want to bind `00` in normal mode to go to the end of line, while `0` will go to the start as usual. Is it possible to achieve something like this with this plugin?

**Comment by max397574** [comment]
yes this is possible
`nnoremap 00 $`

**Comment by axieax** [comment]
> nnoremap 00 $

The issue with this approach is the delay when pressing the first `0` key if I want to jump to the beginning of the line.

**Comment by max397574** [comment]
won't be done by this plugin since this is based only around insert mode
