### ISSUE TITLE
will give error if set to `opt = true` in packer.nvim

### ISSUE THREAD

**Issue by DinkyTrady** [max397574/better-escape.nvim#44]
here is my setup for better escape, if i didn't set to opt true, it still give me error
``` lua
use({"max39757/better-escape.nvim",
  opt = true,
  event = "InsertCharPre",
  config = function()
    require("better_escape").setup()
  end,
})
```  
it is because my all plugins setup in `opt = true` ?

**Comment by max397574** [comment]
use event="InsertEnter"

**Comment by DinkyTrady** [comment]
> use event="InsertEnter"

it will make telescope error

**Comment by max397574** [comment]
most likely an issue with your setup
send the error

**Comment by DinkyTrady** [comment]
@max397574  
so i just try to configure my setup again and didn't use `telescope extensions`, and make `better escape not set as opt plugins`.   
i think this better escape can't use `Packer` keys like `opt, after, event`. i tried with [nvim-zh/better-escape.vim](https://github.com/nvim-zh/better-escape.vim) .

**Comment by max397574** [comment]
ofc it can
I do it myself
it's a problem with your setup
