### ISSUE TITLE
Escape sequences jk & jj delete character before cursor on first use of sequence

### ISSUE THREAD

**Issue by sean-porras** [max397574/better-escape.nvim#45]
This was experienced using AstroNvim, this is the issue and bug report I originally created for them, so all that info is included here.
If this is some sort of collision with something in Astro, I'm not aware of it. Though I was told to submit the issue here.

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.5

### Describe the bug

The first time the escape sequence `jk` is used after opening a file with Astro from the command line without typing anything in insert mode, it will delete the character to the left of the cursor. After the first time, it will work as expected and won't do this.
It won't delete a character if you open another file (eg. in a split window, or in the same window) after already opening the first file. (Eg. if you simply split the window, creating 2 windows of the same file, `jk` will still delete a character if used)
If you type in insert mode after opening a file and then use `jk` to go back to normal mode, it will work as expected, not deleting any characters.
It will delete a newline created by `o` and any additional newlines created by pressing `<Enter>` afterwards (Clarification note: it will delete ONE newline, but will still delete one if you do `o<Enter><Enter>jk` for example).

### Steps to Reproduce

If you don't want to use a file of your own
NOTE: `<SPC f n>` is specific to AstroNvim, if you're just using base Neovim, just do `nvim`
1. Open up a new file with `nvim` then `<SPC f n>` OR `nvim nonexistentfilenamehere.txt`
2. Use `o<Enter Enter (Any number of Enters as you please)>`
3. Use `jk` or `jj` escape sequence
You should see one of the newlines created by either `o` or one of your `<Enter>`s was deleted by the sequence and you have one less newline than expected

To show this works with existing files and characters let's create a `test.txt` file containing
```
hello
world

```
1. Open up the testing file from the command line with `nvim test.txt`
2. You may navigate with HJKL however you may please to put your cursor on the "d" in "world"
3. `ijk` or `ijj` to enter insert mode and use the `jk` or `jj` escape sequence
4. You should see now the file appears as follows
```
hello
word

```
5. You can `:q!` and experiment with this as you would like, if the cursor is on the "w" of "world", you'll end up with
```
helloworld

```

### Expected behavior

All uses of the `jk` or `jj` escape sequences shouldn't delete any character beyond the first `j` which is typed from being in insert mode before the escape sequence is triggered.

**Comment by max397574** [comment]
this isn't a better-escape.nvim issue.
I tried with `repro.lua` and `nvim repro.lua -u repro.lua` and can't reproduce.
```lua
--repro.lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "max397574/better-escape.nvim",
        config = function()
            require("better_escape").setup({
                mapping = { "jj", "jk" },
            })
        end,
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
