### ISSUE TITLE
Not working in Command mode, Visual mode, Operator-pending mode

### ISSUE THREAD

**Issue by howardcochran** [max397574/better-escape.nvim#49]
I really love the idea of this plugin, but it only works for me in Insert mode. Is there a way to enable it for Command mode, Visual mode, and Operator-pending mode?

**Comment by max397574** [comment]
this is because right now the plugin uses an autocommand which only works with insert mode
I have an idea how I could rewrite the plugin to also make it much more powerful that would perhaps allow it to also be used in other modes
I'd have to check though

Command mode might be much easier than the other ones because you can just delete the keys that were entered as the mapping
the other two will be much harder so they might not be possible even with a rewrite

**Comment by max397574** [comment]
I'll close this for now because I won't do this in the near future

**Comment by levinotik** [comment]
+1 for incorporating support for escaping various modes like visual. While better-escape efficiently handles the transition from insert mode, which is often used, I still find myself resorting to `<C-c>` to exit visual and other modes. This leaves the plugin somewhat incomplete, as I'm forced to utilize another escape method, resulting in the need for two distinct sets of key mappings.

**Comment by max397574** [comment]
I actually plan to do something like this on the rewrite branch which you can find here
I just did the insert mode mappings so far but also plan to create options for other modes

**Comment by levinotik** [comment]
> I actually plan to do something like this on the rewrite branch which you can find here I just did the insert mode mappings so far but also plan to create options for other modes

Awesome @max397574! Thanks for the great work. Let us know if/how we can help.

**Comment by Sam-programs** [comment]
> Command mode might be much easier than the other ones because you can just delete the keys that were entered as the mapping

To make this easier you can use c_CTRL-U.

> I just did the insert mode mappings so far but also plan to create options for other modes

Could `vim.on_key` be used as replaced for `InsertCharPre` instead of mappings?

**Comment by Sam-programs** [comment]
Hey could someone try https://github.com/max397574/better-escape.nvim/pull/59, and how is operator pending supposed to work?

**Comment by gmankab** [comment]
> Hey could someone try #59, and how is operator pending supposed to work?

hello

i replaced `max397574/better-escape.nvim` with `Sam-programs/better-escape.nvim` in my lazy.nvim config

then i ran this to reinstall plugins:

`gio trash ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim`

but this plugin still works only in insert mode, and still not works on visual and in command mode

**Comment by Sam-programs** [comment]
> then i ran this to reinstall plugins:
> 
> gio trash ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
> 
> but this plugin still works only in insert mode, and still not works on visual and in command mode
> 
> am i doing something wrong?

I don't know how `gio` works, you should be fine removing just `rm ~/.local/share/nvim/lazy/better-escape.nvim -rf` and reopening neovim.

There was a logic error in my pr that made the plugin only work *half the time* but i doubt that's the issue here.

**Comment by gmankab** [comment]
> I don't know how gio works

it moves dir to trash

**Comment by Sam-programs** [comment]
> it moves dir to trash

Huh it should have worked correctly then, does it work when you remove the better-escape path with `rm ~/.local/share/nvim/lazy/better-escape.nvim -rf` ?

**Comment by rwijtvliet** [comment]
Just a +1 from me for this feature as well. I just want to add the terminal as a mode where users currently have to use "<Esc>" instead of being able to use this plugin.

**Comment by max397574** [comment]
@rwijtvliet there is an open pr for this which I plan to merge in the near future
I have to finish some docs and make sure it doesn't break too much for current users
