### ISSUE TITLE
Document incompatibility with macros in readme.md

### ISSUE THREAD

**Issue by gbroques** [max397574/better-escape.nvim#51]
Hi, thank you for the great plugin!

As a new (Neo)vim user, this was one of the first plugins I installed.

Eventually I learned about macros, and was very confused why macros didn't behave as I expected when escaping insert mode.

I later realized it was because of this plugin when searcing the existing issues (I found https://github.com/max397574/better-escape.nvim/issues/21).

Can we document this is the `readme.md` to inform others before they install this plugin, and hopefully avoid any future confusion for people?

**Comment by max397574** [comment]
I'd be really happy to accept a pr for this
