### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [max397574/better-escape.nvim#56]
Hi, I love and use this plug-in every day. My keyboard's `<ESC>` has been very neglected since this plug-in released :)! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use? Thank you very much!

**Comment by max397574** [comment]
didn't realize that I didn't have a license here yet

**Comment by ColinKennedy** [comment]
Thank you!
