### ISSUE TITLE
Crash after installing new version 'Rewrite'

### ISSUE THREAD

**Issue by mskasal** [max397574/better-escape.nvim#62]
```
E5108: Error executing lua: ...share/nvim/lazy/better-escape.nvim/lua/better_escape.lua:113: attempt to call upvalue 't' (a nil value)                                  
stack traceback:                                                                                                                                                        
        ...share/nvim/lazy/better-escape.nvim/lua/better_escape.lua:113: in function <...share/nvim/lazy/better-escape.nvim/lua/better_escape.lua:109>                  
```

<img width="1515" alt="Screenshot 2024-07-04 at 21 09 47" src="https://github.com/max397574/better-escape.nvim/assets/2426680/dfd3be2b-88f4-472b-8848-d5ba318ba614">

<img width="659" alt="Screenshot 2024-07-04 at 21 13 55" src="https://github.com/max397574/better-escape.nvim/assets/2426680/b45c393f-5b30-4ae3-b2d3-c43ffe2577ac">

**Comment by max397574** [comment]
that is because you're not on latest stable and don't have a function which is used
pushed a fix which should fix this

**Comment by max397574** [comment]
reopen if you still have the issue after updating to the latest commit
