### ISSUE TITLE
Stopped working after the rewrite

### ISSUE THREAD

**Issue by Mugworth** [max397574/better-escape.nvim#68]
I'm on nightly NVIM v0.11.0-dev-211+g37bf4c572a

After the rewrite, better_escape works only once after opening neovim, later it's it does return to normal mode

my config:
 ```
 {
    "max397574/better-escape.nvim",
    event = 'InsertEnter',
    config = function()
      require("better_escape").setup()
    end,
  },
```

Edit: the issue does not show in command mode, i guess i thought it could be because i use have completion window showing after inserting, so i changed jk entry as per instruction on github but with double escape, as in:
```

          i = {
            j = {
              j = "<Esc><Esc>",
              k = "<Esc><Esc>",
            },
            k = {
              j = "<Esc><Esc>",
              k = "<Esc><Esc>",
            }
          },
```
but the issue in insert mode persists

**Comment by Mugworth** [comment]
Ok so after i changed nvim-cmp so that it does not automatically show completion menu, plugin works as expected, still i don't remember having these problems before the rewrite of the plugin, so i'm not closing this issue.

**Comment by max397574** [comment]
I don't really understand what the issue is

if you open neovim and enter insert mode you can use `jk` to escape
and what exactly happens the second time? You say it does return to normal mode which is expected when escaping?

Could you try to provide a minimal template which allows reproducing this issue with this template https://github.com/folke/lazy.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue`?

**Comment by Mugworth** [comment]
Yea i have Esc mapped to closing the cmp menu.

The problem was as follows:
- Open file with nvim
- get inside of insert mode
- jk works
- get into insert mode
- jk doesn't write jk into buffer but also doesn't go out of insert mode(but also don't show nvim-cmp menu now)

Also i'm embarassed because i can't reproduce this error now lol.

I suppose it wasn't error with this plugin but maybe because i had bad internet connection, codeium plugin which i have as entry for nvim-cmp, was lagging behind or smth. Anyway i'm closing it because as i said i can't even reproduce it.

Sorry for wasting your time 😓

**Comment by max397574** [comment]
no worries

the reason this broke things is because we use mapped keys if there are mappings
so if you map <esc>  then mapping <esc> with better-escape will close the cmp menu and not actually esc
which is imo expected
