### ISSUE TITLE
`kkk` exits visual mode with default mappings

### ISSUE THREAD

**Issue by nullromo** [max397574/better-escape.nvim#82]
## Problem
`kkk` exits visual mode.

## Steps to reproduce

0. Use default mappings
1. Open vim
2. Navigate to a line in the middle of the file
3. `vkkk`
4. You will now be in normal mode 😳

I don't think this is intentional.

## Workaround

Use this mapping

```lua
mappings = {
    v = {
        j = {
            k = false,
        }
    }
}
```

**Comment by Sam-programs** [comment]
I can't reproduce this. There was a similar bug, mentioned [here](https://github.com/max397574/better-escape.nvim/issues/73#issuecomment-2216899825), that was fixed in a later version. 

Are you using the latest version of better-escape.nvim ?

**Comment by nullromo** [comment]
Yep, my version was 2 days out of date. That update fixed it. Thanks!
