### ISSUE TITLE
disable for certain tui application

### ISSUE THREAD

**Issue by greeid** [max397574/better-escape.nvim#90]
I''ve used this plugin for a long time but recently i've started to use `lazygit` inside neovim so when I press `j` there it waits for a keypress then only moves down 

I was wondering if there is a setting to disable better escape for a certain application?

**Comment by max397574** [comment]
disable the mappings for terminal mode (see the readme for this)

disable per application is perhaps not even possible and out of scope

**Comment by echaya** [comment]
> disable the mappings for terminal mode (see the readme for this)
> 
> 
> 
> disable per application is perhaps not even possible and out of scope

If it supports function, would it make sense to read buffer/window name and send keys based on matched pattern?

**Comment by max397574** [comment]
You could also do that I guess
